services:
  bucket:
    image: akashvai/bucket:latest
    container_name: akashvai-bucket
    ports:
      - "9090:9090"
      - "9091:9091"
    environment:
      - BUCKET_CONFIG_MACHINE_IP_AUTO_DISCOVERY=true
      - BUCKET_CONFIG_DISK_PATH=/var/bucket
      - BUCKET_CONFIG_HTTP_SERVICE_PORT=9090
      - BUCKET_CONFIG_GRPC_SERVICE_PORT=9091
      - BUCKET_CONFIG_ID=bucket-1
      - SPRING_PROFILES_ACTIVE=local
    volumes:
      - ./:/var/bucket
    