STORAGE_SERVER_MEDIA_CLIENT_URL: "http://localhost:8903/service/v1/medias"
STORAGE_SERVER_MEDIA_CLIENT_API_KEY: "key"
STORAGE_SERVER_REGION_ID: "1"
STORAGE_SERVER_CLUSTER_ID: "1"
STORAGE_SERVER_SECRET_KEY: "secret"
spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer