BUCKET_CONFIG_MACHINE_IP_AUTO_DISCOVERY: true
BUCKET_CONFIG_DISK_PATH: "/home/akash/Development/files"
BUCKET_CONFIG_HTTP_SERVICE_PORT: 9090
BUCKET_CONFIG_GRPC_SERVICE_PORT: 9091
BUCKET_CONFIG_ID: "bucket-1"
spring:
  application:
    name: bucket
server:
  port: ${BUCKET_CONFIG_HTTP_SERVICE_PORT}

