ROUTE_SERVICE_CONFIG_HEARTBEAT_BOOTSTRAP_SERVERS: "localhost:9092"
ROUTE_SERVICE_CONFIG_BUCKET_HEARTBEAT_TOPIC: "buckets"
ROUTE_SERVICE_CONFIG_CLUSTER_ID: 1
ROUTE_SERVICE_CONFIG_BUCKET_LOAD_FACTOR: 2
ROUTE_SERVICE_CONFIG_BUCKET_MANAGER_CLIENT_ADDRESS: "http://localhost:8902"
spring:
  application:
    name: cluster-router
server:
  port: 8904
