server:
  port: 8888
spring:
  application:
    name: crombucket-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: "classpath:/config-files"