JWT_SECRET: "8c1763630733e04d6addfd91ff2a56663c97eaeef1c499595b37b66bb04cadb264130381f80ad494e1b410544869c9168c216a874eaa79f358a07aaa634d858a"
JWT_EXPIRATION: 86400000
spring:
  application:
    name: user-service
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: password
      database: users
      host: "127.0.0.1"
      port: 27017
      auto-index-creation: true
server:
  port: 8901