spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: password
      database: buckets
      host: "127.0.0.1"
      port: 27017
      auto-index-creation: true
server:
  port: 8902