BUCKET_CONFIG_MACHINE_IP_AUTO_DISCOVERY: true
BUCKET_CONFIG_STORAGE_PATH: "/home/akash/Development/files"
BUCKET_CONFIG_GRPC_SERVICE_PORT: 9091
BUCKET_CONFIG_ID: "67af1a136fbc2d145b340c7b"
BUCKET_CONFIG_MEDIA_CLIENT_URL: "http://localhost:8903/api/v1/service/media"
spring:
  application:
    name: bucket
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 9090
